# Generated by Django 3.2.16 on 2022-11-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='deaq_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='deaq_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
