# Generated by Django 3.2.16 on 2022-11-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0005_alter_fashionista_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='deaq_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='garment',
            name='deaq_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
