# Generated by Django 3.2.16 on 2022-11-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0006_auto_20221122_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garment',
            old_name='garment_name',
            new_name='name',
        ),
    ]
