# Generated by Django 4.1.4 on 2023-01-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0007_rename_garment_name_garment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garment",
            name="purchase_price",
            field=models.FloatField(default=0, null=True),
        ),
    ]
