# Generated by Django 4.1.4 on 2023-02-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0009_garment_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="garmentwear",
            old_name="scan_date",
            new_name="date",
        ),
    ]
