# Generated by Django 4.1.4 on 2023-02-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0010_rename_scan_date_garmentwear_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outfitwear",
            old_name="scan_date",
            new_name="date",
        ),
    ]
