# Generated by Django 4.1.4 on 2023-02-03 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0011_rename_scan_date_outfitwear_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfitwear",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
